export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const ERROR_PRODUCT = "ERROR_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART = "UPDATE_CART"; // Assurez-vous que ce type existe
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";